export const CHICKY_OINK_DISPLAY_ORDER = [
  "regular_chicken",
  "spicy_chicken",
  "regular_liempo",
  "spicy_liempo",
  "liog",
  "spicy_liog",
  "poso",
  "atchara_small",
  "atchara_big",
  "coke",
  "sprite",
  "royal",
  "mineral_water",
  "uling",
];
